# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6095dcab87f1849b62fb3e63f59db748fe1530a3fce02a9dd5da450360679b854ee15f72cade4917b3e3829026f67c9d80ea5f05c39a014b3d5e19c24316bdc4

test:
  secret_key_base: c03b613784f1f752b6a200d82ca12dd909aef856d7a45aed007ec9e098355e7fad94572363e2c66d10b2a82a913fc648287d832b062227688d386d5d42b2efd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
